### ISSUE TITLE
Todo do projeto

### ISSUE THREAD

**Issue by Antonio-naddeo** [Antonio-naddeo/taninosflix#3]
## Aulas:

- [x] Aula 1; 
- [x] Aula 2; 
- [x] Aula 3; 
- [x] Aula 4; 
- [ ] Aula 5.

## Desafios:

- [ ] Página 404 personalizada;
- [ ] Slider sem buracos;
- [ ] aumentar videos e mostrar títulos com hover;
- [ ] tocar videos após n segundos com mouse em cima;
- [ ] utilizar api da alura pra alguma coisa massa
